import { Property, Agent, Conversation, SavedSearch, VerificationItem, User } from "@/types"

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "John Okonkwo",
    email: "john@verified.ng",
    phone: "+234 803 123 4567",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    agency: "Prime Realty Ltd",
    verificationStatus: "fully-verified",
    trustScore: 96,
    responseTime: "Under 1 hour",
    memberSince: "2023-01-15",
    listingsCount: 24,
    propertiesSold: 18,
    bio: "Experienced real estate agent specializing in Lagos Island and Yaba properties. Committed to transparent dealings and verified listings only.",
    reviews: [
      {
        id: "rev-1",
        userName: "Chioma N.",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        comment: "John was incredibly professional. The property was exactly as described and the verification process gave me peace of mind.",
        date: "2024-06-15",
        propertyTitle: "2-Bedroom Flat in Yaba",
      },
      {
        id: "rev-2",
        userName: "Emeka O.",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        comment: "Fast response, transparent pricing, no hidden fees. Highly recommend!",
        date: "2024-05-22",
        propertyTitle: "3-Bedroom Duplex in Lekki",
      },
    ],
  },
  {
    id: "agent-2",
    name: "Amina Bello",
    email: "amina@verified.ng",
    phone: "+234 805 987 6543",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    agency: "Bello Properties",
    verificationStatus: "fully-verified",
    trustScore: 92,
    responseTime: "2 hours",
    memberSince: "2023-03-10",
    listingsCount: 17,
    propertiesSold: 12,
    bio: "Abuja-based agent focused on residential properties in Wuse, Maitama, and Gwarinpa. I verify every property personally before listing.",
    reviews: [
      {
        id: "rev-3",
        userName: "Fatima K.",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face",
        rating: 4,
        comment: "Great agent. Property was clean and exactly as shown in photos.",
        date: "2024-06-01",
        propertyTitle: "Self-Contain in Wuse",
      },
    ],
  },
]

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    slug: "2-bedroom-flat-yaba-unilag",
    title: "Modern 2-Bedroom Flat Near UNILAG",
    description: "A beautifully finished 2-bedroom apartment in the heart of Yaba, just 5 minutes walk from UNILAG. Features all ensuite rooms, modern kitchen, 24/7 security, and ample parking. Perfect for students or young professionals.",
    type: "flat",
    status: "active",
    price: 1500000,
    address: "15 Akoka Road, Yaba",
    city: "Lagos",
    state: "Lagos",
    lga: "Yaba",
    neighborhood: "Akoka",
    lat: 6.5244,
    lng: 3.3792,
    bedrooms: 2,
    bathrooms: 2,
    toilets: 3,
    parking: 2,
    furnished: true,
    electricity: "prepaid",
    water: "borehole",
    security: ["gated", "security-guard", "cctv"],
    amenities: ["air-conditioning", "wardrobes", "kitchen-cabinets", "pop-ceiling", "interlocked-compound"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&h=600&fit=crop",
    ],
    ownerId: "owner-1",
    agentId: "agent-1",
    verificationStatus: "fully-verified",
    trustScore: 98,
    availabilityStatus: "available",
    totalMoveInCost: 1890000,
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    agent: mockAgents[0],
    pricingBreakdown: {
      rent: 1500000,
      agencyFee: 150000,
      agreementFee: 50000,
      legalFee: 30000,
      cautionFee: 100000,
      serviceCharge: 60000,
      otherFees: 0,
    },
    propertyHistory: [
      { date: "2024-06-01", event: "Listed", details: "Property listed on VERIFIED" },
      { date: "2024-06-05", event: "Verified", details: "Physical inspection completed by inspector #1042" },
      { date: "2024-06-10", event: "Price Update", details: "Rent adjusted from ₦1,600,000 to ₦1,500,000" },
    ],
    nearby: [
      { name: "University of Lagos", type: "school", distance: "5 min walk" },
      { name: "Yaba College of Technology", type: "school", distance: "10 min walk" },
      { name: "Lagos University Teaching Hospital", type: "hospital", distance: "15 min drive" },
      { name: "Tejuosho Market", type: "market", distance: "8 min drive" },
      { name: "Yaba Bus Terminal", type: "transport", distance: "3 min walk" },
    ],
  },
  {
    id: "prop-2",
    slug: "3-bedroom-duplex-lekki-phase-1",
    title: "Luxury 3-Bedroom Duplex in Lekki Phase 1",
    description: "Stunning 3-bedroom duplex with a private compound in the prestigious Lekki Phase 1. Features a spacious living room, modern fitted kitchen, master's bedroom with walk-in closet, and a serene environment.",
    type: "duplex",
    status: "active",
    price: 4500000,
    address: "12 Admiralty Way, Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    neighborhood: "Lekki Phase 1",
    lat: 6.4413,
    lng: 3.4663,
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    parking: 4,
    furnished: false,
    electricity: "prepaid",
    water: "treated",
    security: ["gated", "security-guard", "cctv", "electric-fence"],
    amenities: ["air-conditioning", "wardrobes", "kitchen-cabinets", "pop-ceiling", "interlocked-compound", "swimming-pool", "gym"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    ],
    ownerId: "owner-2",
    agentId: "agent-1",
    verificationStatus: "fully-verified",
    trustScore: 95,
    availabilityStatus: "available",
    totalMoveInCost: 5400000,
    createdAt: "2024-05-15T09:00:00Z",
    updatedAt: "2024-06-18T11:00:00Z",
    agent: mockAgents[0],
    pricingBreakdown: {
      rent: 4500000,
      agencyFee: 450000,
      agreementFee: 100000,
      legalFee: 50000,
      cautionFee: 200000,
      serviceCharge: 100000,
      otherFees: 0,
    },
    propertyHistory: [
      { date: "2024-05-15", event: "Listed", details: "Property listed on VERIFIED" },
      { date: "2024-05-20", event: "Verified", details: "Physical inspection completed" },
    ],
    nearby: [
      { name: "Lekki British School", type: "school", distance: "5 min drive" },
      { name: "Ebeano Supermarket", type: "market", distance: "3 min drive" },
      { name: "Lekki-Epe Expressway", type: "transport", distance: "2 min drive" },
    ],
  },
  {
    id: "prop-3",
    slug: "self-contain-wuse-abuja",
    title: "Cozy Self-Contain in Wuse 2",
    description: "A clean and secure self-contain apartment in the heart of Wuse 2, Abuja. Perfect for single professionals. Close to major business districts and shopping centers.",
    type: "self-contain",
    status: "active",
    price: 800000,
    address: "45 Aminu Kano Crescent, Wuse 2",
    city: "Abuja",
    state: "FCT",
    lga: "Municipal",
    neighborhood: "Wuse 2",
    lat: 9.0765,
    lng: 7.3986,
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    parking: 1,
    furnished: false,
    electricity: "postpaid",
    water: "borehole",
    security: ["gated", "security-guard"],
    amenities: ["wardrobes", "kitchen-cabinets", "pop-ceiling"],
    images: [
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1484154218962-a1c00207a9a7?w=800&h=600&fit=crop",
    ],
    ownerId: "owner-3",
    agentId: "agent-2",
    verificationStatus: "fully-verified",
    trustScore: 91,
    availabilityStatus: "available",
    totalMoveInCost: 960000,
    createdAt: "2024-06-10T08:00:00Z",
    updatedAt: "2024-06-20T10:00:00Z",
    agent: mockAgents[1],
    pricingBreakdown: {
      rent: 800000,
      agencyFee: 80000,
      agreementFee: 30000,
      legalFee: 20000,
      cautionFee: 20000,
      serviceCharge: 10000,
      otherFees: 0,
    },
    propertyHistory: [
      { date: "2024-06-10", event: "Listed", details: "Property listed on VERIFIED" },
      { date: "2024-06-12", event: "Verified", details: "Physical inspection completed" },
    ],
    nearby: [
      { name: "Wuse Market", type: "market", distance: "5 min walk" },
      { name: "National Hospital", type: "hospital", distance: "10 min drive" },
      { name: "Wuse Bus Stop", type: "transport", distance: "2 min walk" },
    ],
  },
  {
    id: "prop-4",
    slug: "4-bedroom-bungalow-ikeja",
    title: "Spacious 4-Bedroom Bungalow in Ikeja GRA",
    description: "Elegant 4-bedroom bungalow in the serene Ikeja GRA. Features a large compound, boys' quarters, and modern finishing. Ideal for families seeking comfort and security.",
    type: "bungalow",
    status: "active",
    price: 6000000,
    address: "8 Oduduwa Way, Ikeja GRA",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    neighborhood: "Ikeja GRA",
    lat: 6.5957,
    lng: 3.3370,
    bedrooms: 4,
    bathrooms: 4,
    toilets: 5,
    parking: 6,
    furnished: false,
    electricity: "prepaid",
    water: "borehole",
    security: ["gated", "security-guard", "cctv", "electric-fence"],
    amenities: ["air-conditioning", "wardrobes", "kitchen-cabinets", "pop-ceiling", "interlocked-compound", "bq"],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    ],
    ownerId: "owner-4",
    agentId: "agent-1",
    verificationStatus: "fully-verified",
    trustScore: 97,
    availabilityStatus: "available",
    totalMoveInCost: 7200000,
    createdAt: "2024-05-20T07:00:00Z",
    updatedAt: "2024-06-19T16:00:00Z",
    agent: mockAgents[0],
    pricingBreakdown: {
      rent: 6000000,
      agencyFee: 600000,
      agreementFee: 150000,
      legalFee: 75000,
      cautionFee: 300000,
      serviceCharge: 75000,
      otherFees: 0,
    },
    propertyHistory: [
      { date: "2024-05-20", event: "Listed", details: "Property listed on VERIFIED" },
      { date: "2024-05-25", event: "Verified", details: "Physical inspection completed" },
    ],
    nearby: [
      { name: "Ikeja City Mall", type: "mall", distance: "5 min drive" },
      { name: "LASUTH", type: "hospital", distance: "10 min drive" },
      { name: "Murtala Muhammed Airport", type: "transport", distance: "15 min drive" },
    ],
  },
  {
    id: "prop-5",
    slug: "2-bedroom-flat-gwarinpa",
    title: "Affordable 2-Bedroom Flat in Gwarinpa",
    description: "Well-maintained 2-bedroom flat in Gwarinpa Estate. Good road network, constant water supply, and peaceful neighborhood. Great value for money.",
    type: "flat",
    status: "active",
    price: 1200000,
    address: "Phase 3, Gwarinpa Estate",
    city: "Abuja",
    state: "FCT",
    lga: "Municipal",
    neighborhood: "Gwarinpa",
    lat: 9.1044,
    lng: 7.4087,
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    parking: 2,
    furnished: false,
    electricity: "postpaid",
    water: "borehole",
    security: ["gated", "security-guard"],
    amenities: ["wardrobes", "kitchen-cabinets", "pop-ceiling"],
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    ],
    ownerId: "owner-5",
    agentId: "agent-2",
    verificationStatus: "identity-verified",
    trustScore: 78,
    availabilityStatus: "available",
    totalMoveInCost: 1440000,
    createdAt: "2024-06-05T06:00:00Z",
    updatedAt: "2024-06-20T09:00:00Z",
    agent: mockAgents[1],
    pricingBreakdown: {
      rent: 1200000,
      agencyFee: 120000,
      agreementFee: 40000,
      legalFee: 20000,
      cautionFee: 40000,
      serviceCharge: 20000,
      otherFees: 0,
    },
    propertyHistory: [
      { date: "2024-06-05", event: "Listed", details: "Property listed on VERIFIED" },
    ],
    nearby: [
      { name: "Gwarinpa Market", type: "market", distance: "5 min walk" },
      { name: "Nizamiye Hospital", type: "hospital", distance: "10 min drive" },
    ],
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    propertyId: "prop-1",
    propertyTitle: "Modern 2-Bedroom Flat Near UNILAG",
    propertyImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=200&h=150&fit=crop",
    participantId: "agent-1",
    participantName: "John Okonkwo",
    participantAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    participantVerified: true,
    lastMessage: "Yes, the property is still available. When would you like to schedule an inspection?",
    lastMessageAt: "2024-06-20T14:30:00Z",
    unreadCount: 2,
  },
  {
    id: "conv-2",
    propertyId: "prop-2",
    propertyTitle: "Luxury 3-Bedroom Duplex in Lekki Phase 1",
    propertyImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=200&h=150&fit=crop",
    participantId: "agent-1",
    participantName: "John Okonkwo",
    participantAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    participantVerified: true,
    lastMessage: "The service charge covers waste disposal, security, and compound maintenance.",
    lastMessageAt: "2024-06-19T10:15:00Z",
    unreadCount: 0,
  },
]

export const mockSavedSearches: SavedSearch[] = [
  {
    id: "search-1",
    name: "2-Bed in Yaba",
    filters: { city: "Lagos", neighborhood: "Yaba", bedrooms: 2, maxPrice: 2000000 },
    alertFrequency: "daily",
    createdAt: "2024-06-01T10:00:00Z",
  },
  {
    id: "search-2",
    name: "Self-Contain Abuja",
    filters: { city: "Abuja", type: "self-contain", maxPrice: 1000000 },
    alertFrequency: "weekly",
    createdAt: "2024-06-10T08:00:00Z",
  },
]

export const mockVerifications: VerificationItem[] = [
  {
    id: "ver-1",
    type: "identity",
    status: "verified",
    submittedAt: "2024-06-01T10:00:00Z",
    reviewedAt: "2024-06-03T14:00:00Z",
    notes: "Identity verified successfully via NIN and face match.",
    documents: ["nin-front.jpg", "nin-back.jpg", "selfie.jpg"],
  },
  {
    id: "ver-2",
    type: "agency",
    status: "under-review",
    submittedAt: "2024-06-15T09:00:00Z",
    documents: ["cac-cert.pdf", "tax-id.pdf"],
  },
]

export const mockCurrentUser: User = {
  id: "user-1",
  name: "David Emmanuel",
  email: "david@email.com",
  phone: "+234 801 234 5678",
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
  role: "renter",
  verificationStatus: "identity-verified",
  trustScore: 85,
}

export const mockAdminStats = {
  totalUsers: 12543,
  totalListings: 8762,
  pendingVerifications: 234,
  totalRevenue: 45600000,
  fraudReports: 12,
  activeConversations: 1892,
}
