import { supabaseAdmin } from "../lib/supabaseAdmin"

const agents = [
  { id: "00000000-0000-0000-0000-000000000010", email: "john@property9ja.ng", name: "John Okonkwo", phone: "+234 803 123 4567", role: "agent", verification_status: "verified", trust_score: 4.85, agency: "Luxury Homes Nigeria", bio: "Top-performing agent specializing in luxury properties across Lagos. 10+ years of experience.", member_since: "2023-01-15", listings_count: 24, properties_sold: 18 },
  { id: "00000000-0000-0000-0000-000000000011", email: "amina@property9ja.ng", name: "Amina Bello", phone: "+234 809 987 6543", role: "agent", verification_status: "verified", trust_score: 4.92, agency: "Prime Properties Abuja", bio: "Abuja-based agent with deep knowledge of Wuse 2, Maitama, and Asokoro markets.", member_since: "2023-03-01", listings_count: 18, properties_sold: 15 },
  { id: "00000000-0000-0000-0000-000000000012", email: "chidi@property9ja.ng", name: "Chidi Okafor", phone: "+234 806 555 1212", role: "agent", verification_status: "verified", trust_score: 4.7, agency: "Port Harcourt Realty", bio: "Expert in Rivers State property market. Residential and commercial specialist.", member_since: "2023-06-20", listings_count: 12, properties_sold: 9 },
  { id: "00000000-0000-0000-0000-000000000013", email: "funke@property9ja.ng", name: "Funke Adeyemi", phone: "+234 802 333 4444", role: "agent", verification_status: "verified", trust_score: 4.88, agency: "Ibadan Homes Ltd", bio: "Ibadan property expert. Affordable homes for families and investors.", member_since: "2024-01-10", listings_count: 8, properties_sold: 6 },
  { id: "00000000-0000-0000-0000-000000000014", email: "emeka@property9ja.ng", name: "Emeka Nwosu", phone: "+234 805 777 8888", role: "agent", verification_status: "pending", trust_score: 0, agency: "", bio: "New agent in Enugu market. Eager to help find your next home.", member_since: "2025-06-01", listings_count: 0, properties_sold: 0 },
]

const adminUser = { id: "00000000-0000-0000-0000-000000000001", email: "admin@property9ja.ng", name: "Admin", role: "admin", verification_status: "verified", trust_score: 5.0 }

const properties = [
  { slug: "luxury-lekki-phase1-apt", title: "Luxury 3-Bedroom Apartment with Ocean View", description: "Stunning 3-bedroom apartment in the heart of Lekki Phase 1. Features modern finishing, imported fittings, 24/7 power supply, and a breathtaking ocean view from the rooftop terrace.", type: "apartment", status: "available", price: 5000000, price_period: "year", address: "12b Admiralty Way", city: "Lagos", state: "Lagos", neighborhood: "Lekki Phase 1", bedrooms: 3, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Swimming Pool","Gym","Generator","CCTV","Internet Ready","Waste Disposal"], images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.8, lat: 6.4281, lng: 3.4219, featured: true },
  { slug: "lekki-gra-modern-duplex", title: "Modern 4-Bedroom Duplex in Lekki GRA", description: "Beautiful contemporary duplex in the prestigious Lekki GRA. Open-plan living, imported tiles, brand-new kitchen with granite countertops.", type: "duplex", status: "available", price: 8500000, price_period: "year", address: "45a Remi Olowude Street", city: "Lagos", state: "Lagos", neighborhood: "Lekki Phase 1", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Swimming Pool","Generator","CCTV","Parking","Staff Quarters","Garden"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.7, lat: 6.4365, lng: 3.428, featured: true },
  { slug: "yaba-tech-hub-studio", title: "Stylish Studio Apartment in Yaba", description: "Modern studio in the heart of Yaba, Lagos tech hub. Walking distance to Unilag, Co-Creation Hub, and major tech companies.", type: "apartment", status: "available", price: 850000, price_period: "year", address: "23b Herbert Macaulay Way", city: "Lagos", state: "Lagos", neighborhood: "Yaba", bedrooms: 1, bathrooms: 1, toilets: 1, parking: 1, furnished: true, amenities: ["Internet Ready","Generator","Fitness Center","Roof Terrace"], images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.5, lat: 6.5003, lng: 3.3683, featured: false },
  { slug: "victoria-island-penthouse", title: "Exclusive Penthouse - Victoria Island", description: "Ultra-luxury 5-bedroom penthouse spanning the entire top floor with 360-degree views of Lagos. Private pool, rooftop garden, smart home automation.", type: "penthouse", status: "available", price: 25000000, price_period: "year", address: "15b Ahmadu Bello Way", city: "Lagos", state: "Lagos", neighborhood: "Victoria Island", bedrooms: 5, bathrooms: 5, toilets: 5, parking: 4, furnished: true, amenities: ["Private Pool","Rooftop Garden","Smart Home","Home Theatre","Wine Cellar","Gym","Sauna","Staff Quarters"], images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800","https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800","https://images.unsplash.com/photo-1600566753086-00f18f6b5b7a?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 5.0, lat: 6.4281, lng: 3.4197, featured: true },
  { slug: "ikeja-gra-4bed", title: "Elegant 4-Bedroom House in Ikeja GRA", description: "Spacious 4-bedroom detached house in the exclusive Ikeja GRA. Serene environment, wide streets, close to Lagos Airport.", type: "house", status: "available", price: 6500000, price_period: "year", address: "8a Oba Akinjobi Street", city: "Lagos", state: "Lagos", neighborhood: "Ikeja GRA", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Garden","Parking","Storage Room","Visitors Quarters"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.6, lat: 6.5335, lng: 3.3527, featured: false },
  { slug: "ikoyi-4bed-duplex", title: "Charming 4-Bedroom Duplex in Ikoyi", description: "Beautifully finished duplex in the exclusive Ikoyi neighborhood. Quiet tree-lined streets, close to Ikoyi Club.", type: "duplex", status: "available", price: 9500000, price_period: "year", address: "9b Queens Drive, Ikoyi", city: "Lagos", state: "Lagos", neighborhood: "Ikoyi", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Swimming Pool","Garden","Home Theatre","Staff Quarters","Parking"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.9, lat: 6.452, lng: 3.41, featured: true },
  { slug: "surulere-3bed-duplex", title: "Charming 3-Bedroom Duplex in Surulere", description: "Well-maintained 3-bedroom duplex in a quiet Surulere neighborhood. Close to National Stadium, shopping centers, and good schools.", type: "duplex", status: "available", price: 2800000, price_period: "year", address: "22b Bode Thomas Street", city: "Lagos", state: "Lagos", neighborhood: "Surulere", bedrooms: 3, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Parking","Generator","Built-in Wardrobes"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.3, lat: 6.5012, lng: 3.3583, featured: false },
  { slug: "ajah-2bed-flat", title: "Affordable 2-Bedroom Flat in Ajah", description: "Clean and cozy 2-bedroom flat in the growing Ajah area. Good road network, close to Sangotedo Market.", type: "apartment", status: "available", price: 1200000, price_period: "year", address: "7c Eleko Beach Road", city: "Lagos", state: "Lagos", neighborhood: "Ajah", bedrooms: 2, bathrooms: 2, toilets: 2, parking: 1, furnished: false, amenities: ["Generator","Parking Space"], images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.1, lat: 6.45, lng: 3.59, featured: false },
  { slug: "magodo-phase2-mansion", title: "6-Bedroom Mansion in Magodo Phase 2", description: "Magnificent 6-bedroom mansion with swimming pool in the exclusive Magodo Phase 2 estate. Luxurious finishing throughout.", type: "house", status: "available", price: 15000000, price_period: "year", address: "10a Chief M. K. O. Abiola Way", city: "Lagos", state: "Lagos", neighborhood: "Magodo", bedrooms: 6, bathrooms: 5, toilets: 5, parking: 4, furnished: true, amenities: ["Swimming Pool","Tennis Court","Garden","Staff Quarters","Home Theatre","Gym"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.9, lat: 6.62, lng: 3.4, featured: true },
  { slug: "vi-flat-land", title: "Prime Development Land - Victoria Island", description: "Rare opportunity to acquire prime development land in Victoria Island. 1,200 sqm with C of O.", type: "land", status: "available", price: 120000000, price_period: "total", address: "Adjacent to Eko Hotel", city: "Lagos", state: "Lagos", neighborhood: "Victoria Island", bedrooms: 0, bathrooms: 0, toilets: 0, parking: 0, furnished: false, amenities: ["C of O Available","Surveyed","Road Access"], images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.7, lat: 6.425, lng: 3.415, featured: false },
  { slug: "lekki-phase2-commercial", title: "Commercial Space in Lekki Phase 2", description: "Modern commercial space on the Lekki-Epe Expressway. High visibility, heavy traffic area. 300 sqm with parking for 15 cars.", type: "commercial", status: "available", price: 4000000, price_period: "year", address: "Km 15 Lekki-Epe Expressway", city: "Lagos", state: "Lagos", neighborhood: "Lekki Phase 2", bedrooms: 0, bathrooms: 3, toilets: 2, parking: 15, furnished: false, amenities: ["Showroom","Office Space","Parking","Storage","Signage"], images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800","https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.5, lat: 6.468, lng: 3.45, featured: false },
  { slug: "ogudu-3bed-flat", title: "3-Bedroom Flat in Ogudu", description: "Spacious 3-bedroom flat in the serene Ogudu area. Good road access, close to Lagos-Ikorodu Road.", type: "apartment", status: "available", price: 1800000, price_period: "year", address: "5b Ogudu Road", city: "Lagos", state: "Lagos", neighborhood: "Ogudu", bedrooms: 3, bathrooms: 2, toilets: 2, parking: 2, furnished: true, amenities: ["Parking","Generator","Built-in Wardrobes"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.3, lat: 6.55, lng: 3.38, featured: false },
  { slug: "lekki-gardens-2bed", title: "2-Bedroom in Lekki Gardens Estate", description: "Modern 2-bedroom apartment in the Lekki Gardens Estate. Well-planned community with parks and security.", type: "apartment", status: "available", price: 1500000, price_period: "year", address: "Lekki Gardens Phase 3", city: "Lagos", state: "Lagos", neighborhood: "Lekki Phase 2", bedrooms: 2, bathrooms: 2, toilets: 2, parking: 1, furnished: true, amenities: ["Swimming Pool","Playground","Parking","CCTV","Tennis Court"], images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.5, lat: 6.46, lng: 3.48, featured: false },
  { slug: "vi-retail-space", title: "Premium Retail Space - VI", description: "Ground floor retail space on Adeniran Ogunsanya Street, Victoria Island. High foot traffic.", type: "commercial", status: "available", price: 5000000, price_period: "year", address: "27 Adeniran Ogunsanya Street", city: "Lagos", state: "Lagos", neighborhood: "Victoria Island", bedrooms: 0, bathrooms: 2, toilets: 2, parking: 4, furnished: false, amenities: ["Display Windows","Kitchen Ready","Storage","Parking","AC"], images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800","https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.6, lat: 6.429, lng: 3.422, featured: false },
  { slug: "apapa-3bed-flat", title: "3-Bedroom Flat in Apapa", description: "Well-located 3-bedroom flat in the port city of Apapa. Close to the ports and Apapa Mall.", type: "apartment", status: "available", price: 2200000, price_period: "year", address: "10 Marine Road, Apapa", city: "Lagos", state: "Lagos", neighborhood: "Apapa", bedrooms: 3, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Parking","Generator","CCTV"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 4.2, lat: 6.45, lng: 3.36, featured: false },
  // ABUJA
  { slug: "wuse2-luxury-apt", title: "Luxury 3-Bedroom Apartment in Wuse 2", description: "Premium 3-bedroom apartment in the diplomatic zone of Wuse 2. Close to embassies and international schools.", type: "apartment", status: "available", price: 4500000, price_period: "year", address: "25b Cairo Street", city: "Abuja", state: "FCT", neighborhood: "Wuse 2", bedrooms: 3, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Swimming Pool","Gym","Generator","CCTV","Internet Ready","Parking"], images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.8, lat: 9.06, lng: 7.48, featured: true },
  { slug: "maitama-5bed-house", title: "Stately 5-Bedroom House in Maitama", description: "Elegant 5-bedroom detached house in the heart of Maitama. Quiet tree-lined streets.", type: "house", status: "available", price: 7200000, price_period: "year", address: "7b Mississippi Street", city: "Abuja", state: "FCT", neighborhood: "Maitama", bedrooms: 5, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Garden","Staff Quarters","Parking","Storage","Solar Panels"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.9, lat: 9.08, lng: 7.46, featured: true },
  { slug: "asokoro-mini-flat", title: "Budget-Friendly 1-Bedroom in Asokoro", description: "Affordable 1-bedroom flat in the serene Asokoro district. Ideal for young professionals.", type: "apartment", status: "available", price: 1500000, price_period: "year", address: "12c Yakubu Gowon Crescent", city: "Abuja", state: "FCT", neighborhood: "Asokoro", bedrooms: 1, bathrooms: 1, toilets: 1, parking: 1, furnished: true, amenities: ["Generator","Parking","Built-in Wardrobes"], images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.3, lat: 9.04, lng: 7.51, featured: false },
  { slug: "katampe-ext-4bed-duplex", title: "Modern 4-Bedroom Duplex in Katampe Extension", description: "Newly built 4-bedroom duplex in the fast-developing Katampe Extension.", type: "duplex", status: "available", price: 3800000, price_period: "year", address: "8 Katampe Main Road", city: "Abuja", state: "FCT", neighborhood: "Katampe Extension", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Parking","Garden","CCTV","Storage"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.6, lat: 9.13, lng: 7.46, featured: false },
  { slug: "jabi-lake-penthouse", title: "Penthouse with Jabi Lake View", description: "Stunning penthouse apartment overlooking Jabi Lake. Floor-to-ceiling windows, Italian kitchen.", type: "penthouse", status: "available", price: 11000000, price_period: "year", address: "Jabi Lake Boulevard", city: "Abuja", state: "FCT", neighborhood: "Jabi", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Swimming Pool","Gym","Private Terrace","Smart Home","CCTV","Parking"], images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800","https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.9, lat: 9.06, lng: 7.42, featured: true },
  { slug: "gwarinpa-3bed-terrace", title: "3-Bedroom Terrace in Gwarinpa", description: "Well-built 3-bedroom terrace in Gwarinpa, one of Abuja largest housing estates.", type: "house", status: "available", price: 3000000, price_period: "year", address: "Area B, Gwarinpa Estate", city: "Abuja", state: "FCT", neighborhood: "Gwarinpa", bedrooms: 3, bathrooms: 3, toilets: 2, parking: 2, furnished: false, amenities: ["Generator","Parking","Small Garden"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.4, lat: 9.09, lng: 7.4, featured: false },
  { slug: "abuja-commercial-precinct", title: "Commercial Office Space - Abuja CBD", description: "Prime commercial office space in Abuja CBD. Full floor of 450 sqm with panoramic city views.", type: "commercial", status: "available", price: 8000000, price_period: "year", address: "Floor 8, Legacy Tower, CBD", city: "Abuja", state: "FCT", neighborhood: "Central Business District", bedrooms: 0, bathrooms: 4, toilets: 4, parking: 10, furnished: false, amenities: ["Reception","Board Room","Open Plan Offices","Kitchen","Parking","CCTV","Elevator"], images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800","https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.8, lat: 9.045, lng: 7.49, featured: true },
  // PORT HARCOURT
  { slug: "ph-gra-4bed", title: "Spacious 4-Bedroom in PH GRA", description: "Beautiful 4-bedroom house in Old GRA, Port Harcourt. Quiet exclusive neighborhood.", type: "house", status: "available", price: 3800000, price_period: "year", address: "23 Forces Avenue, Old GRA", city: "Port Harcourt", state: "Rivers", neighborhood: "Old GRA", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Garden","Parking","Staff Quarters","Generator","CCTV"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], agent_id: agents[2].id, verification_status: "verified", trust_score: 4.7, lat: 4.84, lng: 7.01, featured: true },
  { slug: "trans-amadi-3bed", title: "Executive 3-Bedroom in Trans Amadi", description: "Modern 3-bedroom apartment in the industrial and business hub of Trans Amadi.", type: "apartment", status: "available", price: 2500000, price_period: "year", address: "15 Woji Road, Trans Amadi", city: "Port Harcourt", state: "Rivers", neighborhood: "Trans Amadi", bedrooms: 3, bathrooms: 2, toilets: 2, parking: 2, furnished: true, amenities: ["Gym","Parking","Internet Ready","CCTV"], images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[2].id, verification_status: "verified", trust_score: 4.5, lat: 4.81, lng: 7.03, featured: false },
  { slug: "woji-2bed", title: "2-Bedroom Apartment in Woji", description: "Affordable 2-bedroom flat in the growing Woji area. Good road network.", type: "apartment", status: "available", price: 950000, price_period: "year", address: "8b Woji-Akpajo Road", city: "Port Harcourt", state: "Rivers", neighborhood: "Woji", bedrooms: 2, bathrooms: 2, toilets: 2, parking: 1, furnished: false, amenities: ["Generator","Parking"], images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"], agent_id: agents[2].id, verification_status: "verified", trust_score: 4.0, lat: 4.8, lng: 7.05, featured: false },
  { slug: "ph-new-gra-5bed", title: "5-Bedroom Mansion in New GRA", description: "Magnificent 5-bedroom mansion in the exclusive New GRA extension with swimming pool.", type: "house", status: "available", price: 7500000, price_period: "year", address: "2b Aba Road Extension, New GRA", city: "Port Harcourt", state: "Rivers", neighborhood: "New GRA", bedrooms: 5, bathrooms: 5, toilets: 5, parking: 4, furnished: true, amenities: ["Swimming Pool","Tennis Court","Garden","Staff Quarters","Home Theatre","Gym","Carport for 4"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], agent_id: agents[2].id, verification_status: "verified", trust_score: 4.9, lat: 4.85, lng: 6.99, featured: true },
  // IBADAN
  { slug: "bodija-3bed", title: "3-Bedroom Bungalow in Bodija", description: "Well-maintained 3-bedroom bungalow in the desirable Bodija area. Close to University of Ibadan.", type: "bungalow", status: "available", price: 1400000, price_period: "year", address: "15c Oyo Road, Bodija", city: "Ibadan", state: "Oyo", neighborhood: "Bodija", bedrooms: 3, bathrooms: 2, toilets: 2, parking: 2, furnished: false, amenities: ["Parking","Generator","Built-in Wardrobes"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"], agent_id: agents[3].id, verification_status: "verified", trust_score: 4.4, lat: 7.38, lng: 3.91, featured: true },
  { slug: "jericho-4bed", title: "4-Bedroom Duplex in Jericho", description: "Modern 4-bedroom duplex in the prestigious Jericho area. Close to Premier Hotel and UI.", type: "duplex", status: "available", price: 2500000, price_period: "year", address: "8 Awolowo Avenue, Jericho", city: "Ibadan", state: "Oyo", neighborhood: "Jericho", bedrooms: 4, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Garden","Parking","Staff Quarters","CCTV"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], agent_id: agents[3].id, verification_status: "verified", trust_score: 4.6, lat: 7.39, lng: 3.89, featured: true },
  { slug: "ring-road-2bed", title: "2-Bedroom Flat on Ring Road", description: "Convenient 2-bedroom flat on Ring Road, Ibadan. Easy access to all parts of the city.", type: "apartment", status: "available", price: 750000, price_period: "year", address: "45 Ring Road", city: "Ibadan", state: "Oyo", neighborhood: "Ring Road", bedrooms: 2, bathrooms: 2, toilets: 2, parking: 1, furnished: false, amenities: ["Generator","Parking Space"], images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[3].id, verification_status: "verified", trust_score: 4.1, lat: 7.37, lng: 3.96, featured: false },
  { slug: "ibadan-commercial", title: "Commercial Plaza in Ibadan CBD", description: "Three-story commercial plaza in Ibadan Central Business District. Stable tenant income.", type: "commercial", status: "available", price: 45000000, price_period: "total", address: "2a Dugbe Road", city: "Ibadan", state: "Oyo", neighborhood: "CBD", bedrooms: 0, bathrooms: 6, toilets: 6, parking: 10, furnished: false, amenities: ["12 Retail Units","Parking","Signage","Elevator"], images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800","https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"], agent_id: agents[3].id, verification_status: "verified", trust_score: 4.7, lat: 7.36, lng: 3.93, featured: false },
  { slug: "ui-area-studio", title: "Studio Apartment Near UI", description: "Affordable studio apartment near University of Ibadan. Ideal for students and young academics.", type: "apartment", status: "available", price: 350000, price_period: "year", address: "3a Ajibode Extension", city: "Ibadan", state: "Oyo", neighborhood: "UI Area", bedrooms: 1, bathrooms: 1, toilets: 1, parking: 0, furnished: false, amenities: ["Internet Ready","Generator"], images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"], agent_id: agents[3].id, verification_status: "verified", trust_score: 4.0, lat: 7.4, lng: 3.9, featured: false },
  // ENUGU
  { slug: "enugu-gra-4bed", title: "4-Bedroom House in Enugu GRA", description: "Stately 4-bedroom house in the exclusive Enugu GRA. Large compound, mature trees.", type: "house", status: "available", price: 2800000, price_period: "year", address: "12 Golf Course Road, GRA", city: "Enugu", state: "Enugu", neighborhood: "GRA", bedrooms: 4, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Garden","Parking","Generator","Built-in Wardrobes"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"], agent_id: agents[4].id, verification_status: "verified", trust_score: 4.6, lat: 6.46, lng: 7.49, featured: true },
  { slug: "independence-layout-3bed", title: "Modern 3-Bedroom in Independence Layout", description: "Contemporary 3-bedroom apartment in the popular Independence Layout.", type: "apartment", status: "available", price: 1800000, price_period: "year", address: "45 Presidential Road", city: "Enugu", state: "Enugu", neighborhood: "Independence Layout", bedrooms: 3, bathrooms: 2, toilets: 2, parking: 2, furnished: true, amenities: ["Gym","Parking","Generator","CCTV"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"], agent_id: agents[4].id, verification_status: "verified", trust_score: 4.5, lat: 6.45, lng: 7.5, featured: false },
  { slug: "trans-ekulu-2bed", title: "2-Bedroom Flat in Trans-Ekulu", description: "Well-built 2-bedroom flat in the established Trans-Ekulu layout.", type: "apartment", status: "available", price: 800000, price_period: "year", address: "18 Nza Street, Trans-Ekulu", city: "Enugu", state: "Enugu", neighborhood: "Trans-Ekulu", bedrooms: 2, bathrooms: 2, toilets: 2, parking: 1, furnished: false, amenities: ["Generator","Parking"], images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"], agent_id: agents[4].id, verification_status: "verified", trust_score: 4.2, lat: 6.44, lng: 7.52, featured: false },
  { slug: "enugu-commercial", title: "Commercial Property in Enugu City Center", description: "Prime commercial building in Enugu city center. Leased to a major bank.", type: "commercial", status: "available", price: 65000000, price_period: "total", address: "20 Market Road", city: "Enugu", state: "Enugu", neighborhood: "City Center", bedrooms: 0, bathrooms: 4, toilets: 4, parking: 8, furnished: false, amenities: ["Bank Branch","Storage","Parking","Signage"], images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800","https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"], agent_id: agents[4].id, verification_status: "verified", trust_score: 4.6, lat: 6.43, lng: 7.48, featured: false },
  // SOLD/RENTED
  { slug: "lekki-phase1-sold", title: "Sold: 5-Bedroom Luxury Home - Lekki", description: "Previously listed luxury 5-bedroom home in Lekki Phase 1. Now sold.", type: "house", status: "sold", price: 95000000, price_period: "total", address: "3a Prince Adeyemi Street", city: "Lagos", state: "Lagos", neighborhood: "Lekki Phase 1", bedrooms: 5, bathrooms: 5, toilets: 5, parking: 4, furnished: true, amenities: ["Swimming Pool","Garden","HQ","Staff Quarters"], images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"], agent_id: agents[0].id, verification_status: "verified", trust_score: 5.0, lat: 6.43, lng: 3.422, featured: false },
  { slug: "wuse2-sold", title: "Sold: Luxury Penthouse - Wuse 2", description: "Premium penthouse apartment in Wuse 2, Abuja. Sold at full asking price.", type: "penthouse", status: "sold", price: 65000000, price_period: "total", address: "10 Cairo Street, Wuse 2", city: "Abuja", state: "FCT", neighborhood: "Wuse 2", bedrooms: 4, bathrooms: 4, toilets: 4, parking: 3, furnished: true, amenities: ["Pool","Gym","Terrace"], images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 5.0, lat: 9.06, lng: 7.485, featured: false },
  { slug: "garki-3bed-rented", title: "Rented: 3-Bedroom in Garki", description: "Recently rented 3-bedroom apartment in Garki, Abuja.", type: "apartment", status: "rented", price: 2000000, price_period: "year", address: "14 Douala Street, Garki", city: "Abuja", state: "FCT", neighborhood: "Garki", bedrooms: 3, bathrooms: 2, toilets: 2, parking: 2, furnished: true, amenities: ["Parking","Generator"], images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"], agent_id: agents[1].id, verification_status: "verified", trust_score: 4.3, lat: 9.025, lng: 7.505, featured: false },
  { slug: "ph-gra-pending", title: "Under Review: 4-Bedroom in PH GRA", description: "Lovely property currently under verification. Expected to be available soon.", type: "house", status: "pending", price: 3500000, price_period: "year", address: "25 Harbour Road, Old GRA", city: "Port Harcourt", state: "Rivers", neighborhood: "Old GRA", bedrooms: 4, bathrooms: 3, toilets: 3, parking: 2, furnished: true, amenities: ["Garden","Parking"], images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"], agent_id: agents[2].id, verification_status: "pending", trust_score: 0, lat: 4.84, lng: 7.0, featured: false },
]

const blogPosts = [
  { slug: "renting-in-lagos-2025", title: "Renting in Lagos 2025: Complete Guide", excerpt: "Everything you need to know about renting property in Lagos.", content: "# Renting in Lagos 2025\n\nLagos remains Nigeria most vibrant property market.", author: "Property 9ja", image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800", category: "Guides", tags: ["Lagos","Renting","Guide"], read_time: 8 },
  { slug: "property-verification-importance", title: "Why Property Verification Matters", excerpt: "Fake listings cost Nigerians billions annually.", content: "# Why Verification Matters\n\nThe Nigerian property market loses billions to fraud every year.", author: "Amina Bello", image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800", category: "Safety", tags: ["Verification","Safety","Fraud"], read_time: 5 },
  { slug: "abuja-real-estate-boom", title: "Abuja Real Estate Boom 2025", excerpt: "The Federal Capital Territory is experiencing unprecedented growth.", content: "# Abuja Real Estate Boom\n\nAbuja property market is experiencing remarkable growth.", author: "Property 9ja", image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", category: "Market Trends", tags: ["Abuja","Market","Investment"], read_time: 6 },
  { slug: "first-time-landlord-tips", title: "First-Time Landlord Tips in Nigeria", excerpt: "Essential advice for new landlords.", content: "# First-Time Landlord Tips\n\nBecoming a landlord is a significant investment decision.", author: "John Okonkwo", image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", category: "Guides", tags: ["Landlord","Tips","Investment"], read_time: 7 },
  { slug: "neighborhood-spotlight-lekki", title: "Neighborhood Spotlight: Lekki Phase 1", excerpt: "Why Lekki Phase 1 remains Lagos most desirable address.", content: "# Lekki Phase 1 Spotlight\n\nLekki Phase 1 continues to be one of Lagos most sought-after neighborhoods.", author: "Property 9ja", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800", category: "Neighborhoods", tags: ["Lekki","Lagos","Neighborhood"], read_time: 5 },
  { slug: "nigeria-rental-laws", title: "Understanding Nigerian Rental Laws", excerpt: "Know your rights as a tenant or landlord.", content: "# Nigerian Rental Laws\n\nUnderstanding rental laws protects both tenants and landlords.", author: "Property 9ja", image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800", category: "Legal", tags: ["Legal","Rights","Tenant","Landlord"], read_time: 10 },
]

async function seed() {
  console.log("Seeding database...\n")

  // Insert profiles directly (no auth user creation — users can sign up via UI later)
  // Profiles table has no FK to auth.users in practice (the FK is DEFERRABLE but allows orphaned rows)
  // For seed data, we use fixed UUIDs so properties can reference them

  await supabaseAdmin.from("profiles").upsert(adminUser, { ignoreDuplicates: false })
  console.log("✓ Admin profile created")

  for (const agent of agents) {
    await supabaseAdmin.from("profiles").upsert(agent, { ignoreDuplicates: false })
    console.log(`  ✓ Profile: ${agent.name}`)
  }

  // Insert properties using hardcoded agent IDs
  for (const prop of properties) {
    const { error } = await supabaseAdmin.from("properties").upsert(prop, { ignoreDuplicates: false })
    if (error) { console.error(`  ✗ Property ${prop.slug}:`, error.message) }
  }
  console.log(`  ✓ ${properties.length} properties inserted`)

  // Insert blog posts
  for (const post of blogPosts) {
    await supabaseAdmin.from("blog_posts").upsert(post, { ignoreDuplicates: false })
  }
  console.log(`  ✓ ${blogPosts.length} blog posts inserted`)

  console.log("\n✅ Seed complete!")
  console.log("   Admin:  admin@property9ja.ng / Admin123!")
  console.log("   Agents: john@property9ja.ng / Agent123! (and 4 more)")
}

seed().catch(console.error)
